### ISSUE TITLE
ark_merlin

### ISSUE THREAD

**Issue by burdges** [arkworks-rs/sponge#20]
Apologies if this is naive question, but is this sponge crate meant just to provide hashing inside a SNARK or should it also provide things like a transcript type implementing `ark_std::io::Write` so that `ark_ff::bytes::ToBytes` works?  If brief, does ark_merlin make any sense?

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by weikengchen** [comment]
If for generality, yes. Currently, as you can see, the sponge crate is providing help for a developer to implement Fiat-Shamir. All the operations to the sponge --- aka all the transcript values --- need to be executed via separate calls to the sponge.

There is a reason we do so --- when it comes to running a sponge inside the constraint system, you want more control over what values you put into the sponge. For example, if I have a field element and I want to put it into a Poseidon sponge, I would try to not convert it to bytes first (which is costly in the constraint world). This concern leads to why the sponge at this moment is providing the low-level interfaces, while the high-level ones (io::Write) are deferred, due to no urgent need from a use case (often those can do pretty well with Blake2).

**Comment by burdges** [comment]
Cool.  I always mostly bought HdV's argument that complex protocols should never use bake2, etc. directly, but instead define their own bespoke extension trait for transcripts.  I suppose this view should mesh well with snark friendly transcripts once they stabilize somewhat.  Thanks!
